version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: peneirada-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: peneirada
      MYSQL_USER: peneirauser
      MYSQL_PASSWORD: peneira123
      TZ: America/Fortaleza
      LANG: C.UTF-8
    ports:
      - "3307:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
