name: Deploy automático

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1) Checkout do repositório
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Carrega a chave SSH
      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Homolog (develop)
      - name: Deploy Homolog (develop)
        if: github.ref == 'refs/heads/develop'
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o BatchMode=yes \
              -tt \
              -p ${{ secrets.SSH_PORT }} \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -euo pipefail
      
            REMOTE_DIR="/var/www/PI-V_equipe3"   # <-- AJUSTE AQUI
            cd "$REMOTE_DIR"
      
            docker-compose -f docker-compose.yml down --remove-orphans || true
      
            # Atualiza código (o servidor precisa ter credenciais para ler o repo)
            git fetch origin
            git checkout develop
            git pull origin develop
      
            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml up -d --build
      
            exit 0
          EOF

