name: Deploy automático

on:
  push:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Falha cedo se o secret não estiver presente
      - name: Assert SSH_PRIVATE_KEY is present
        run: |
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "ERRO: Secret SSH_PRIVATE_KEY ausente ou vazio."
            exit 1
          fi

      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      # Teste rápido de conectividade e permissão no host remoto
      - name: Test SSH connectivity
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" -o BatchMode=yes -o StrictHostKeyChecking=yes \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "echo 'SSH OK em' \$(hostname) && exit 0"

      # --- Deploy para develop (homolog) ---
      - name: Deploy Homolog (develop)
        if: github.ref == 'refs/heads/develop'
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" << 'EOF'
            set -euo pipefail
            cd /caminho/do/projeto

            # Se usa Compose v2, troque docker-compose -> docker compose
            docker-compose -f docker-compose.yml down --remove-orphans || true

            # ATENÇÃO: o servidor precisa ter credenciais para git pull (SSH/PAT/Deploy Key)
            git fetch origin
            git checkout develop
            git pull origin develop

            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml up -d --build
          EOF
     
