name: Deploy automático

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1) Checkout do repositório
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Carrega a chave SSH
      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy Homolog (develop)
        if: github.ref == 'refs/heads/develop'
        run: |
          ssh -o StrictHostKeyChecking=no -o BatchMode=yes \
              -p "${{ secrets.SSH_PORT }}" \
              "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" << 'EOF'
            set -euo pipefail
      
            REMOTE_DIR="/var/www/PI-V_equipe3"             # << ajuste se precisar
            REPO_URL="git@github.com:natorjunior/PI-V_equipe3.git"  # ou HTTPS+PAT
            BRANCH="develop"
      
            # 1) preparar diretório (sem sudo no workflow; faça o chown 1x manualmente se precisar)
            mkdir -p "$REMOTE_DIR"
            cd "$REMOTE_DIR"
      
            # 2) clonar na primeira vez OU atualizar se já existe
            if [ ! -d .git ]; then
              git init
              git remote add origin "$REPO_URL" || git remote set-url origin "$REPO_URL"
              git fetch origin "$BRANCH" --depth=1
              git checkout -b "$BRANCH" "origin/$BRANCH"
            else
              git remote set-url origin "$REPO_URL"
              git fetch origin
              git checkout "$BRANCH"
              git reset --hard "origin/$BRANCH"
            fi
      
            # 3) escolher docker compose v2 ou v1
            if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
              COMPOSE="docker compose"
            else
              COMPOSE="docker-compose"
            fi
      
            # 4) subir stack
            \$COMPOSE -f docker-compose.yml down --remove-orphans || true
            \$COMPOSE -f docker-compose.yml pull
            \$COMPOSE -f docker-compose.yml up -d --build
            exit 0
          EOF
