name: Deploy autom치tico

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1) Checkout do reposit칩rio
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Carrega a chave SSH
      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy (develop)
        if: github.ref == 'refs/heads/develop'
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o BatchMode=yes \
              -p "${{ secrets.SSH_PORT }}" \
              "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" << 'EOF'
            set -euo pipefail
            REMOTE_DIR="/var/www/PI-V_equipe3"
            cd "$REMOTE_DIR"
      
            # Compose v1/v2
            if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
              COMPOSE="docker compose"
            else
              COMPOSE="docker-compose"
            fi
      
            # Atualiza c칩digo (servidor precisa ter credencial pr칩pria!)
            git fetch origin
            git checkout develop
            git reset --hard origin/develop
      
            $COMPOSE -f docker-compose.yml down --remove-orphans || true
            $COMPOSE -f docker-compose.yml pull
            $COMPOSE -f docker-compose.yml up -d --build
            exit 0
          EOF
